/*----------------------------------------------------------------------------*/
/*
  This file is generated by Code_Saturne, a general-purpose CFD tool.
*/
/*----------------------------------------------------------------------------*/

#include "cs_defs.h"

/*----------------------------------------------------------------------------
 * Standard C library headers
 *----------------------------------------------------------------------------*/

#include <assert.h>
#include <math.h>

#if defined(HAVE_MPI)
#include <mpi.h>
#endif

/*----------------------------------------------------------------------------
 *  Local headers
 *----------------------------------------------------------------------------*/

#include "cs_headers.h"

/*----------------------------------------------------------------------------*/

BEGIN_C_DECLS

/*----------------------------------------------------------------------------*/

void
cs_meg_post_profiles(const char       *name,
                     int               n_coords,
                     cs_real_t         coords[][3])
{
  /* User-defined coordinates for profile AXE
    ----------------------------------------- */

  if (strcmp(name, "AXE") == 0) {
    cs_real_t x, y, z;

    for (int p_id = 0; p_id < n_coords; p_id++) {
      cs_real_t s = (cs_real_t)p_id / (cs_real_t)(n_coords-1);

      x = 0;
      y = 0;
      z = s * 1.5;

      coords[p_id][0] = x;
      coords[p_id][1] = y;
      coords[p_id][2] = z;
    }
  }

  /* User-defined coordinates for profile Z003
    ------------------------------------------ */

  if (strcmp(name, "Z003") == 0) {
    cs_real_t x, y, z;

    for (int p_id = 0; p_id < n_coords; p_id++) {
      cs_real_t s = (cs_real_t)p_id / (cs_real_t)(n_coords-1);

      x = s * 0.15;
      y = 0;
      z = 0.003;

      coords[p_id][0] = x;
      coords[p_id][1] = y;
      coords[p_id][2] = z;
    }
  }

  /* User-defined coordinates for profile Z080
    ------------------------------------------ */

  if (strcmp(name, "Z080") == 0) {
    cs_real_t x, y, z;

    for (int p_id = 0; p_id < n_coords; p_id++) {
      cs_real_t s = (cs_real_t)p_id / (cs_real_t)(n_coords-1);

      x = s * 0.15;
      y = 0;
      z = 0.08;

      coords[p_id][0] = x;
      coords[p_id][1] = y;
      coords[p_id][2] = z;
    }
  }

  /* User-defined coordinates for profile Z160
    ------------------------------------------ */

  if (strcmp(name, "Z160") == 0) {
    cs_real_t x, y, z;

    for (int p_id = 0; p_id < n_coords; p_id++) {
      cs_real_t s = (cs_real_t)p_id / (cs_real_t)(n_coords-1);

      x = s * 0.15;
      y = 0;
      z = 0.16;

      coords[p_id][0] = x;
      coords[p_id][1] = y;
      coords[p_id][2] = z;
    }
  }

  /* User-defined coordinates for profile Z240
    ------------------------------------------ */

  if (strcmp(name, "Z240") == 0) {
    cs_real_t x, y, z;

    for (int p_id = 0; p_id < n_coords; p_id++) {
      cs_real_t s = (cs_real_t)p_id / (cs_real_t)(n_coords-1);

      x = s * 0.15;
      y = 0;
      z = 0.24;

      coords[p_id][0] = x;
      coords[p_id][1] = y;
      coords[p_id][2] = z;
    }
  }

  /* User-defined coordinates for profile Z320
    ------------------------------------------ */

  if (strcmp(name, "Z320") == 0) {
    cs_real_t x, y, z;

    for (int p_id = 0; p_id < n_coords; p_id++) {
      cs_real_t s = (cs_real_t)p_id / (cs_real_t)(n_coords-1);

      x = s * 0.15;
      y = 0;
      z = 0.32;

      coords[p_id][0] = x;
      coords[p_id][1] = y;
      coords[p_id][2] = z;
    }
  }

  /* User-defined coordinates for profile Z420
    ------------------------------------------ */

  if (strcmp(name, "Z420") == 0) {
    cs_real_t x, y, z;

    for (int p_id = 0; p_id < n_coords; p_id++) {
      cs_real_t s = (cs_real_t)p_id / (cs_real_t)(n_coords-1);

      x = s * 0.15;
      y = 0;
      z = 0.42;

      coords[p_id][0] = x;
      coords[p_id][1] = y;
      coords[p_id][2] = z;
    }
  }
}

/*----------------------------------------------------------------------------*/

END_C_DECLS

