#!/bin/sh

PREFIX=`dirname $0`
PREFIX=`cd "$PREFIX/.." ; pwd`
SUBDIR=`basename $PREFIX`

ARCHNAME=ple.tar
\rm -f $ARCHNAME.gz

RUNDIR=`pwd`

if [ `uname -s` = Linux ] ; then
  TMPDIR=`mktemp -d /tmp/ple_backup.XXXXXX`
else
  TMPDIR=/tmp/ple_backup_`basename $0`
  mkdir $TMPDIR
fi
if [ $? -ne 0 ]; then
  echo "$0: Error creating temporary directory"
  exit 1
fi

cp -p -r $PREFIX $TMPDIR/
cd $TMPDIR || exit 1

# Nettoyage de la copie

find "$TMPDIR" -name *~ -exec \rm {} \;
find "$TMPDIR" -name \#* -exec \rm {} \;
find "$TMPDIR" -name \.\#* -exec \rm {} \;
find "$TMPDIR" -name .svn -exec \rm -rf {} \;

PREFIX_BASE=`basename $PREFIX`

tar cvf $ARCHNAME $PREFIX_BASE

gzip $ARCHNAME
mv $ARCHNAME.gz $RUNDIR

cd $RUNDIR
\rm -rf $TMPDIR

