.\"-------------------------------------------------------------------------------
.\"
.\" This file is part of Code_Saturne, a general-purpose CFD tool.
.\"
.\" Copyright (C) 1998-2013 EDF S.A.
.\"
.\" This program is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU General Public License as published by the Free Software
.\" Foundation; either version 2 of the License, or (at your option) any later
.\" version.
.\"
.\" This program is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
.\" FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
.\" details.
.\"
.\" You should have received a copy of the GNU General Public License along with
.\" this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
.\" Street, Fifth Floor, Boston, MA 02110-1301, USA.
.\"
.\"-------------------------------------------------------------------------------
.\"
.TH CODE_SATURNE 1 2009-10-27 "" "Code_Saturne commands"
.SH NAME
code_saturne \- Main user script of Code_Saturne.
.SH SYNOPSIS
.B code_saturne
.RI [-h|--help]
.RI <command>
.br
.SH DESCRIPTION
The
.B code_saturne
script is the main user script of Code_Saturne.
.\"
.\" Options description
.SH OPTIONS
.B
.IP "-h, --help"
Help message.
.\"
.\" Commands description
.SH COMMANDS
Further information will be obtain with
.B "code_saturne <command> --help"
.B
.IP "check_consistency"
The
.B "code_saturne check_consistency"
command checks the consistency between the user files and the Xml file
(from the Graphical User Interface) provided by the user and, if
needed, that the chosen options are compatible with parallel
calculations. Lastly, it prints the chosen specific physics.

.B
.IP "check_mesh"
The
.B "code_saturne check_mesh"
command verify the quality of a given mesh. The following options will
be passed to Code_Saturne preprocessor.

.B
.IP "compile"
The
.B "code_saturne compile"
command can be used to generate the
.B cs_solver
executable needed for running a Code_Saturne study.

.B
.IP "create"
The
.B "code_saturne create"
command sets up a directory structure for a Code_Saturne study or
case. The different directories created are MESH for meshes, POST for
user post-processing and a case directory (or several) containing a
DATA, SRC (to store user files), RESU (to store results) and SCRIPTS
directory.

.B
.IP "info"
The
.B "code_saturne info"
command is a wrapper for an easier look at Code_Saturne documentation.
.\"
.\" References
.SH SEE ALSO
.BR cs_io_dump (1),
.BR cs_partition (1),
.BR cs_preprocess (1),
.BR cs_solver (1)
