#!/bin/sh

for fich in listing_* ; do
  fich2=`basename $fich .last`
  if [ "$fich2" = "$fich" ] ; then
    arch=`echo $fich |cut -c9-30`
#HP-UX
    if [ "$arch" = "HP-UX" ] ; then
      grep -v "/tmp/" $fich        |grep -v "f90" | grep -v "Compiled" > ${fich}.mod
      grep -v "/tmp/" ${fich}.last |grep -v "f90" | grep -v "Compiled" > ${fich}.last.mod
#IRIX64
    elif [ "$arch" = "IRIX64" ] ; then  
      grep -v "f77" $fich         > ${fich}.mod
      grep -v "f77" ${fich}.last  > ${fich}.last.mod
#Linux
    elif [ "$arch" = "Linux" ] ; then  
      grep -v "gfortran" $fich        |grep -v "/tmp" |grep -v "gcc" > ${fich}.mod
      grep -v "gfortran" ${fich}.last |grep -v "/tmp" |grep -v "gcc" > ${fich}.last.mod
#Linux_CCRT
    elif [ "$arch" = "Linux_CCRT" ] ; then  
      grep -v "mpif77" $fich        > ${fich}.mod
      grep -v "mpif77" ${fich}.last > ${fich}.last.mod
#Linux_Ch
    elif [ "$arch" = "Linux_Ch" ] ; then
      grep -v "mpif77" $fich        |grep -v "/tmp" > ${fich}.mod
      grep -v "mpif77" ${fich}.last |grep -v "/tmp" > ${fich}.last.mod
#OSF1
    elif [ "$arch" = "OSF1" ] ; then  
      grep -v "f90" $fich        > ${fich}.mod
      grep -v "f90" ${fich}.last > ${fich}.last.mod
#SunOS
    elif [ "$arch" = "SunOS" ] ; then  
      grep -v "f77" $fich        |grep -v "/tmp" > ${fich}.mod
      grep -v "f77" ${fich}.last |grep -v "/tmp" > ${fich}.last.mod
    fi
    gtkdiff --geometry 1100x850 ${fich}.mod ${fich}.last.mod
    rm -f ${fich}.mod ${fich}.last.mod
  fi
done

exit
