#!/bin/sh

PREFIX=`dirname $0`
PREFIX=`cd "$PREFIX/.." ; pwd`
SUBDIR=`basename $PREFIX`

ARCHNAME=${SUBDIR}.tar.xz

RUNDIR=`pwd`

cd $PREFIX/.. || exit 1

PREFIX_BASE=`basename $PREFIX`

tar cvJf $ARCHNAME --exclude='.*.swp' \
                   --exclude='build' \
                   --exclude='arch' \
                   --exclude='neptune_cfd' \
                   --exclude=$ARCHNAME \
                   $PREFIX_BASE

mv $ARCHNAME $RUNDIR

cd $RUNDIR

