#!/bin/sh

if [ ! -d sbin ]; then
  echo "$0 must be called from top directory (../$0)"
  exit 1
fi

for d in `\ls`; do
  if test -f $d/sbin/bootstrap; then
    (cd $d && ./sbin/bootstrap)
  fi
done

# Remove unversioned files added by previous bootstrap

for f in `ls ./build-aux` ; do
  case $f in
    *.py | catalyst* | *.makefile | list_modules.sh) ;;
    *) rm -f ./build-aux/$f ;;
  esac
done

rm -rf m4/codeset.m4 m4/extern-inline.m4 m4/fcntl-o.m4 m4/gettext.m4 \
       m4/glibc2.m4 m4/glibc21.m4 m4/iconv.m4 m4/intdiv0.m4 \
       m4/intl.m4 m4/intldir.m4 m4/intlmacosx.m4 m4/intmax.m4 \
       m4/inttypes-pri.m4 m4/inttypes_h.m4 m4/lcmessage.m4 \
       m4/lock.m4 m4/longlong.m4 m4/lib-ld.m4 m4/lib-link.m4 \
       m4/lib-prefix.m4 m4/libtool.m4 m4/lt~obsolete.m4 \
       m4/ltoptions.m4 m4/ltsugar.m4 m4/ltversion.m4 m4/nls.m4 \
       m4/printf-posix.m4 m4/po.m4 m4/progtest.m4 m4/size_max.m4 \
       m4/stdint_h.m4 m4/threadlib.m4 m4/uintmax_t.m4 m4/visibility.m4 \
       m4/wchar_t.m4 m4/wint_t.m4 m4/xsize.m4

# Prefer autoreconf to separate stages when possible

type autopoint > /dev/null 2>&1

if test $? = 0 ; then

  autoreconf -vif $@

else

  echo "running aclocal"
  aclocal -I config

  echo "running autoconf"
  autoconf

  if [ ! -f config/ltmain.sh ]; then
    echo "running libtoolize"
    libtoolize --force --copy
  fi

  echo "running autoheader"
  autoheader

  echo "running automake"
  automake -a -c

fi

# Remove cache directory
\rm -rf autom4te.cache
