#!/bin/sh

prefix=`dirname $0`
. $prefix/../bin/cs_profile

echo Compilation for architecture $NOM_ARCH

rm -f listing_${NOM_ARCH} 
if [ "$1" = "-test" ] ; then
  ./install 1>listing_${NOM_ARCH} 2>&1   
else
  ./install -DBG && ./install 1>listing_${NOM_ARCH} 2>&1
fi

exit


