#!/bin/sh

if [ ! -d sbin ]; then
  echo "$0 must be called from top directory (../$0)"
  exit 1
fi

package_gnu=''
msgid_bugs_address='saturne-support@edf.fr'

cd po

echo "running xgettext"
case `xgettext --version | sed 1q | sed -e 's,^[^0-9]*,,'` in
  '' | 0.[0-9] | 0.[0-9].* | 0.1[0-5] | 0.1[0-5].* | 0.16 | 0.16.[0-1]*)
    xgettext --default-domain=ncs --directory=.. \
      --add-comments=TRANSLATORS: --keyword=_ --keyword=N_ --from-code=ISO_8859-15  \
      --files-from=../po/POTFILES.in \
      --copyright-holder='EDF S.A.' \
      --msgid-bugs-address="$msgid_bugs_address";;
  *)
    xgettext --default-domain=ncs --directory=.. \
      --add-comments=TRANSLATORS: --keyword=_ --keyword=N_ --from-code=ISO_8859-15  \
      --files-from=../po/POTFILES.in \
      --copyright-holder='EDF S.A.' \
      --package-name="${package_gnu}ncs" \
      --package-version='1.3.6' \
      --msgid-bugs-address="$msgid_bugs_address";;
esac

if test -f ncs.po; then
  if test -f ./ncs.pot; then
    sed -f remove-potcdate.sed < ./ncs.pot > ncs.1po
    sed -f remove-potcdate.sed < ncs.po > ncs.2po
    if cmp ncs.1po ncs.2po >/dev/null 2>&1; then
      rm -f ncs.1po ncs.2po ncs.po
    else
      rm -f ncs.1po ncs.2po ./ncs.pot
      mv ncs.po ./ncs.pot
    fi
  else
    mv ncs.po ./ncs.pot
  fi
fi

if test ! -f fr.po; then
  echo "running msginit"
  msginit --locale=fr --no-translator
fi

if test ! -f fr.gmo; then
  echo "running msgmerge"
  msgmerge --update fr.po ncs.pot
  echo "running msgfmt"
  msgfmt -c --statistics -o fr.gmo fr.po
fi

touch stamp-po

