.\"
.\"  This file is part of the Code_Saturne Kernel, element of the
.\"  Code_Saturne CFD tool.
.\"
.\"  Copyright (C) 2009 EDF S.A., France
.\"
.\"  contact: saturne-support@edf.fr
.\"
.\"  The Code_Saturne Kernel is free software; you can redistribute it
.\"  and/or modify it under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2 of
.\"  the License, or (at your option) any later version.
.\"
.\"  The Code_Saturne Kernel is distributed in the hope that it will be
.\"  useful, but WITHOUT ANY WARRANTY; without even the implied warranty
.\"  of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License
.\"  along with the Code_Saturne Preprocessor; if not, write to the
.\"  Free Software Foundation, Inc.,
.\"  51 Franklin St, Fifth Floor,
.\"  Boston, MA  02110-1301  USA
.\"
.TH CS_CHECK_MESH 1 2009-03-15 "" "Code_Saturne commands"
.SH NAME
cs_check_mesh \- Launch Code_Saturne preprocessor and solver in
verification mode on a given mesh.
.SH SYNOPSIS
.B cs_check_mesh
.RI -m
.RI <file>
.RI [preprocessor_options]
.br
.SH DESCRIPTION
The
.B cs_check_mesh
script verify the quality of a given mesh. The following options will
be passed to Code_Saturne preprocessor.
.SH OPTIONS
.B
.IP "-m, --mesh <file>"
Preprocessor input mesh file (mesh file format determined
automatically by filename extension or forced by
.B -format
sub-option)

.PP
.I General options
.B
.IP "-h, --help"
Print a usage message and exit.
.B
.IP "-i, --in [<file>]"
Command line completed by a file (default file: standard input)
.B
.IP "--int-face [<sub-options>]"
Count and display interior faces these faces may be selected with
face-selection sub-options
.B
.IP "-j, --join [<sub-options>]"
Join non-conforming faces; select faces to join with face-selection
sub-options
.B
.IP "-p, --perio <sub-options>"
Mesh periodicity defined by argument; joining sub-options for
tolerances and selection of periodic faces with face-selection
sub-options
.B
.IP "--reorient"
If necessary, correct orientation of cells and faces

.PP
.I Mesh selection sub-options (-m, --mesh)
.B
.IP "--format <keyword>"
Selection of mesh file format
.B
.IP "--num <n>"
Selection of mesh number in file (if the format allows it)
.B
.IP "--grp-cel <keyword>"
Add groups of cells (based on format features/conventions)
  * based on sections: keyword "section"
  * based on zones:    keyword "zone"
.B
.IP "--grp-fac <keyword>"
Add groups of faces (based on format features/conventions)
  * based on sections: keyword "section"
  * based on zones:    keyword "zone"

.PP
.I Available mesh formats (-m, --mesh; --format)

                                 Extension      Keyword

   CGNS                          .cgns          cgns     
   pro-STAR/STAR4                .ngeom         ngeom    
   EnSight (6 or Gold)           .case          ensight  
   GAMBIT Neutral                .neu           gambit   
   GMSH                          .msh           gmsh     
   NUMECA Hex                    .hex           hex      
   I-deas universal              .unv           unv      
   MED                           .med           med      
   Simail (NOPO)                 .des           des      
   Meta-mesh file                .mesh          meta     

.PP
.I Periodicity sub-options (-p, --perio)
.B
.IP "--trans <tx ty tz>"
Translation vector
.B
.IP "--rota --angle <alpha> --dir <dx dy dz> [--invpt <px py pz>]"
Rotation defined by an angle (in degrees) and a direction vector, and
eventually by an invariant point (origin by default)
.B
.IP "--rota --matrix <mij> [--invpt <px py pz>]"
Rotation defined by the rotation matrix (given line by line), and
eventually by an invariant point (origin by default)

.PP
.I Non-conformal face joining sub-options (-j, --join, -p, --perio)
.B
.IP "--fraction <real number>"
Fraction of the length of the smallest edge under which we consider
that vertices may be fused (default value: 0.1)
.B
.IP "--plane <real number>"
Minimal cosine of the normals of 2 coplanar faces (default value: 0.8)
.B
.IP "--semi-conf"
Fast joining algorithm (allowed if faces already share vertices)

.PP
.I Face selection sub-options (for joining, selection, and periodicity)
.B
.IP "--color <number(s)>"
Color numbers of faces to select
.B
.IP "--group <name(s)>"
Group names of faces to select
.B
.IP "--invsel"
Invert selection
.SH SEE ALSO
.BR cs_check_consistency (1),
.BR cs_create (1),
.BR cs_preprocess (1)
