#!/bin/sh

if [ ! -d sbin ]; then
  echo "$0 must be called from top directory (../$0)"
  exit 1
fi

echo "running aclocal"
aclocal -I m4

echo "running autoconf"
autoconf

if [ ! -f build-aux/ltmain.sh ]; then
  echo "running libtoolize"
  libtoolize --force --copy
fi

echo "running autoheader"
autoheader

echo "running automake"
automake -a -c

echo "removing autom4te.cache"
\rm -rf autom4te.cache

